export const MissionEvents = {
    MISSION_LOADED: 'MISSION_LOADED',
    MISSION_BRIEFING_START: 'MISSION_BRIEFING_START',
    MISSION_STARTED: 'MISSION_STARTED',
    OBJECTIVE_ADDED: 'OBJECTIVE_ADDED',
    OBJECTIVE_COMPLETED: 'OBJECTIVE_COMPLETED',
    OBJECTIVE_FAILED: 'OBJECTIVE_FAILED',
    EXTRACTION_AVAILABLE: 'EXTRACTION_AVAILABLE',
    MISSION_COMPLETED: 'MISSION_COMPLETED',
    MISSION_FAILED: 'MISSION_FAILED',
    TARGET_IDENTIFIED: 'TARGET_IDENTIFIED',
    TARGET_MEASURED: 'TARGET_MEASURED',
    TARGET_ELIMINATED: 'TARGET_ELIMINATED'
};
